name: Random Assign

on:
  workflow_call:
    inputs:
      user:
        required: true
        type: string
      repo:
        required: true
        type: string
      number:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  random-assign-codeowners:
  if: inputs.user == 'dependabot' || inputs.user == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: master
          path: ${{ inputs.repo }}
          token: ${{ secrets.token }}
      - name: random assign
        env:
          NUMBER: ${{ inputs.number }}
          REPO: ${{ inputs.path }}
      - run: |
          tail ./$REPO/.github/CODEOWNERS -n 1 |
            tr -d '@' |
            sed s/^\*\ // |
            sed s/\ /\\n/g |
            shuf -n 1 |
            xargs gh pr edit $NUMBER --add-assignee
        with:
          token: ${{ secrets.token }}
