name: Random Assign

on:
  workflow_call:
    inputs:
      user:
        required: true
        type: string
      repo:
        required: true
        type: string
      number:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  random-assign-codeowners:
    runs-on: ubuntu-latest
    # if: ${{ inputs.user }} == 'dependabot' || ${{ inputs.user }} == 'dependabot[bot]'

    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: random assign
          env:
            NUMBER: ${{ inputs.number }}
            REPO: ${{ inputs.path }}
            GITHUB_TOKEN: ${{ secrets.token }}
          run: |
            tail ./$REPO/.github/CODEOWNERS -n 1 |
              tr -d '@' |
              sed s/^\*\ // |
              sed s/\ /\\n/g |
              shuf -n 1 |
              xargs gh pr edit $NUMBER --add-assignee
